import math

# Generated by ChatGPT from my PowerShell code...didn't touch a thing!

def stare_at_stones(blinks, setup):
    last_state = setup

    for count in range(1, blinks + 1):
        print(f"Current blink: {count}/{blinks}")
        new_state = []

        for value in last_state:
            if value == 0:
                new_state.append(1)
            elif len(str(value)) % 2 == 0:
                value_str = str(value)
                mid = len(value_str) // 2
                left = int(value_str[:mid])
                right = int(value_str[mid:])
                new_state.extend([left, right])
            else:
                new_state.append(value * 2024)

        print(f"Current Stone Count: {len(new_state)}")
        if count < blinks:
            last_state = new_state

    return f"The total number of stones after {blinks} blinks is: {len(new_state)}"

# Read input from the file
with open("input", "r") as file:
    puzzle_input = file.read().strip()

# Parse the input into a list of integers
initial_state = list(map(int, puzzle_input.split()))

# Call the function with the specified parameters
result_25_blinks = stare_at_stones(25, initial_state)
print(result_25_blinks)

result_75_blinks = stare_at_stones(75, initial_state)
print(result_75_blinks)
